spring:
  profiles:
    active: dev
  thymeleaf:
    cache: false

mybatis:
  typeAliasesPackage: com.example.entity
  mapperLocations: classpath*:mapper/*.xml


---

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    #生产 pom连接改成6.0.6
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://rm-uf66g46zo0208e5deio.mysql.rds.aliyuncs.com:3306/springdemo?useUnicode=true&characterEncoding=UTF-8
#    username: root
#    password: Root0513
    #本地
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://182.61.23.13:3306/springdemo?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    username: root
    password: root123
    #最大活跃数
    maxActive: 20
    #初始化数量
    initialSize: 1
    #最大连接等待超时时间
    maxWait: 60000
    #打开PSCache，并且指定每个连接PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    #通过connectionProperties属性来打开mergeSql功能；慢SQL记录
    #connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 1 from dual
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    #配置监控统计拦截的filters，去掉后监控界面sql将无法统计,'wall'用于防火墙
    filters: stat, wall, log4j
  jpa:
    properties:
      hibernate:
        database: mysql
        show_sql: true
        format_sql: true
  #配置redis数据库连接
#  redis:
#    host: 127.0.0.1
#    port: 6379
#    pool:
#    max-idle: 20
#    min-idle: 1
#    max-active: 20
#    max-wait: 60000
#    database: 0 #默认是索引为的0的数据库
