spring:
  profiles:
    active: dev
  thymeleaf:
    cache: false

mybatis:
  typeAliasesPackage: com.example.entity
  mapperLocations: classpath*:mapper/*.xml


---

spring:
  profiles: dev

  datasource:
    url: jdbc:mysql://localhost:3306/springdemo?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    dbcp2:
      initial-size: 5
      min-idle: 5
      max-wait-millis: 60000